version: '3'
services:


  cf:
    container_name: ubuntu
    image: ubuntu
    stdin_open: true
    tty: true
    restart: always
    volumes: 
      - mysql_confd:/docker/mysql/conf.d
      - mysql_data:/docker/mysql/data
      - mysql_initdb:/docker/mysql/initdb


  onlyoffice-mysql-server:
    container_name: onlyoffice-mysql-server
    image: mysql:5.7.21
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=onlyoffice
    networks:
     - onlyoffice
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - mysql_confd:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql
      - mysql_initdb:/docker-entrypoint-initdb.d

  onlyoffice-community-server:
    container_name: onlyoffice-community-server
    image: onlyoffice/communityserver:latest
    environment:
      - MYSQL_SERVER_ROOT_PASSWORD=my-secret-pw
      - MYSQL_SERVER_DB_NAME=onlyoffice
      - MYSQL_SERVER_HOST=onlyoffice-mysql-server
      - MYSQL_SERVER_USER=onlyoffice_user
      - MYSQL_SERVER_PASS=onlyoffice_pass 
      - DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server
    networks:
     - onlyoffice
    ports:
     - '80:80'
     - '443:443'
     - '5222:5222'
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - CommunityServer_data:/var/www/onlyoffice/Data
      - CommunityServer_logs:/var/log/onlyoffice

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
    expose:
      - '80'
      - '443'
    volumes:
    - DocumentServer_logs:/var/log/onlyoffice 
    - DocumentServer_data:/var/www/onlyoffice/Data 
    - DocumentServer_lib:/var/lib/onlyoffice
    - DocumentServer_db:/var/lib/postgresql

  onlyoffice-mail-server:
    container_name: onlyoffice-mail-server
    image: onlyoffice/mailserver:latest
    depends_on:
     - onlyoffice-mysql-server
    hostname: 192.168.99.100.xip.io
    environment:
      - MYSQL_SERVER=onlyoffice-mysql-server
      - MYSQL_SERVER_PORT=3306
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWD=my-secret-pw
      - MYSQL_SERVER_DB_NAME=onlyoffice_mailserver
    networks:
      - onlyoffice
    restart: always
    privileged: true
    ports: ['25:25','143:143','587:587']
    stdin_open: true
    tty: true
    expose:
      - '8081'
    volumes:
      - onlyoffice_MailServer_data_vmail:/var/vmail
      - onlyoffice_MailServer_data_certs:/etc/pki/tls/mailserver
      - onlyoffice_MailServer_logs:/var/log
networks:
  onlyoffice:
    driver: 'bridge'

volumes:
  mysql_data:
  mysql_confd:  
  mysql_initdb:
  CommunityServer_data:
  CommunityServer_logs:
  DocumentServer_logs:
  DocumentServer_data:
  DocumentServer_lib:
  DocumentServer_db:
  onlyoffice_MailServer_data_vmail:
  onlyoffice_MailServer_data_certs:
  onlyoffice_MailServer_logs:
